config/routes.rb
Rails.application.routes.draw do
  get "users/show"
  root "home#index"

  devise_for :users

  resources :chatrooms do
    resources :messages
  end

  namespace :api do
    namespace :v1 do
      resources :users
      resources :chatrooms, only: [ :index, :create ]
      resources :messages, only: [ :create ]
      post "/log_in", to: "users#login"
      post "/sign_up", to: "users#sign_up"
      post "/initiate_chatroom", to: "chatrooms#initiate_chatroom"
    end
  end

  resources :users, only: [ :index ]

  get "user/:id", to: "users#show", as: "user"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="login">
    <div class="item">
        <h2>Welcome to MeowChat</h2>
        <div class="meow_list_button">
            <% if current_user %>
            <%= link_to "Start Chatting", chatrooms_path, class:"btn btn-primary" %>
            <%= link_to 'Sign Out', destroy_user_session_path, data: {turbo_method: :delete}, class:"nav-link" %>
            <% else %>
            <%= link_to "Log In", new_user_session_path, class:"btn btn-primary"  %>
            <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-primary" %>
            <% end %>
        </div>
    </div>
    <div class="item">
        <h2>Updated React Web!</h2>
        <div class="meow_list_button">
            <%= link_to "React Website", "https://meowchat-fe-vg3t2.ondigitalocean.app", class:"btn btn-primary" %>
        </div>
    </div>
</div>